### ISSUE TITLE
Only one ctdb metric output

### ISSUE THREAD

**Issue by bds006** [jf-guillou/ctdb_exporter#2]
Hello, 
When I run the exporter on the CTDB node, there is only one metric related:  "ctdb_up 1", all of the others seems not for ctdb, below is the metrics output :

=========quota==========================
"# HELP ctdb_up Is CTDB running
“# TYPE ctdb_up gauge
ctdb_up 1
”# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
"# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
"# HELP go_goroutines Number of goroutines that currently exist.
"# TYPE go_goroutines gauge
go_goroutines 11
"# HELP go_info Information about the Go environment.
"# TYPE go_info gauge
go_info{version="go1.14"} 1
"# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
"# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 487912

"# HELP go_memstats_frees_total Total number of frees.
"# TYPE go_memstats_frees_total counter
go_memstats_frees_total 93
.
.
.
.
”# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.“
"# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 0
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
===============unquote========================

There are no metrics like "ctdb_banned" or "ctdb_num_clients"

Did I miss anything to do? 
Thanks in advance!
Dan

**Comment by bds006** [comment]
weird , another CTDB cluster returns the values for "ctdb_inactive" , "ctdb_banned", "ctdb_unhealthy", the exporter should be working, I'd close the issue. thanks!

**Comment by jf-guillou** [comment]
Hello,

Just to be clear, the `go_` metrics are automatically generated by the golang prometheus library.

Metrics like `ctdb_banned` will only be returned by the master node (ctdb pnn), the remaining nodes should only return `ctdb_up`, which seems to be consistent with your description.
